/**
 * Files panel and Search Tool card copy (C6.1), in en / pt / zh. Same pattern
 * as the room catalog (`group-room-text.ts`): keys are `area.name`, plural pairs
 * end in `_one` / `_other`, `{name}` placeholders are filled by
 * `filesSearchText` (group-room-locale.ts). The en table defines the key set;
 * pt and zh must have the same keys (type-checked here, and by the parity test
 * for the placeholder sets). File names, paths and search results are user
 * data and never come from here.
 */

export const FILES_SEARCH_TEXT_EN = {
  "files.hideTree": "Hide file tree",
  "files.showTree": "Show file tree",
  "files.toggleTree": "Toggle file tree",
  "files.filterPlaceholder": "Filter files...",
  "files.empty": "Empty",
  "files.noWorkspace": "No workspace",
  "files.noMatches": "No matches",
  "files.resizeTree": "Resize file tree",
  "files.unsavedChanges": "Unsaved changes",
  "files.options": "File options",
  "files.copyPath": "Copy Path",
  "files.copyContents": "Copy File Contents",
  "files.wordWrap": "Word Wrap",
  "files.openContainingFolderMenu": "Open Containing Folder",
  "files.open": "Open",
  "files.openContainingFolder": "Open containing folder",
  "files.selectFile": "Select a file from the workspace tree",
  "files.noFileOpen": "No file open",
  "files.binaryNoPreview": "Binary file — no preview.",
  "files.previewTruncated": "preview truncated",
  "files.workspaceFallback": "workspace",
  "files.keptDraftNotice": "Unsaved changes — the line may have moved",
  "files.dialogTitle": "Save changes to {name}?",
  "files.dialogDescription": "You have unsaved changes. If you discard them, they will be lost.",
  "files.save": "Save",
  "files.discard": "Discard",
  "files.cancel": "Cancel",
  "files.saveFailed": "Couldn't save: {message}",
  "search.found_one": "Found {count} result",
  "search.found_other": "Found {count} results",
  "search.outsideWorkspace": "outside workspace",
  "search.outsideTitle": "Outside the workspace: {path}",
  "search.outsideLabel": "{path} (outside the workspace)",
  "search.openAtLine": "Open {path} at line {line}",
  "search.open": "Open {path}",
  "search.openMatch": "Open {path} at line {line}: {text}",
  "search.showMatches_one": "Show {count} match in {path}",
  "search.showMatches_other": "Show {count} matches in {path}",
  "search.hideMatches_one": "Hide {count} match in {path}",
  "search.hideMatches_other": "Hide {count} matches in {path}",
  "search.searchingWeb": "Searching the web…",
  "search.searching": "Searching…",
  "search.searchedFor": "Searched for",
  "search.queryIn": "{pattern} in {path}",
  "search.line": "L{line}",
  "search.matches_one": "{count} match",
  "search.matches_other": "{count} matches",
  "search.dir": "dir",
} as const;

export type FilesSearchTextKey = keyof typeof FILES_SEARCH_TEXT_EN;

export const FILES_SEARCH_TEXT_PT: Record<FilesSearchTextKey, string> = {
  "files.hideTree": "Ocultar árvore de arquivos",
  "files.showTree": "Mostrar árvore de arquivos",
  "files.toggleTree": "Alternar árvore de arquivos",
  "files.filterPlaceholder": "Filtrar arquivos...",
  "files.empty": "Vazio",
  "files.noWorkspace": "Sem workspace",
  "files.noMatches": "Nenhum resultado",
  "files.resizeTree": "Redimensionar árvore de arquivos",
  "files.unsavedChanges": "Alterações não salvas",
  "files.options": "Opções do arquivo",
  "files.copyPath": "Copiar caminho",
  "files.copyContents": "Copiar conteúdo do arquivo",
  "files.wordWrap": "Quebra de linha",
  "files.openContainingFolderMenu": "Abrir pasta do arquivo",
  "files.open": "Abrir",
  "files.openContainingFolder": "Abrir pasta do arquivo",
  "files.selectFile": "Selecione um arquivo na árvore do workspace",
  "files.noFileOpen": "Nenhum arquivo aberto",
  "files.binaryNoPreview": "Arquivo binário — sem pré-visualização.",
  "files.previewTruncated": "pré-visualização truncada",
  "files.workspaceFallback": "workspace",
  "files.keptDraftNotice": "Alterações não salvas — a linha pode ter mudado",
  "files.dialogTitle": "Salvar as alterações em {name}?",
  "files.dialogDescription":
    "Você tem alterações não salvas. Se descartá-las, elas serão perdidas.",
  "files.save": "Salvar",
  "files.discard": "Descartar",
  "files.cancel": "Cancelar",
  "files.saveFailed": "Não foi possível salvar: {message}",
  "search.found_one": "{count} resultado encontrado",
  "search.found_other": "{count} resultados encontrados",
  "search.outsideWorkspace": "fora do workspace",
  "search.outsideTitle": "Fora do workspace: {path}",
  "search.outsideLabel": "{path} (fora do workspace)",
  "search.openAtLine": "Abrir {path} na linha {line}",
  "search.open": "Abrir {path}",
  "search.openMatch": "Abrir {path} na linha {line}: {text}",
  "search.showMatches_one": "Mostrar {count} ocorrência em {path}",
  "search.showMatches_other": "Mostrar {count} ocorrências em {path}",
  "search.hideMatches_one": "Ocultar {count} ocorrência em {path}",
  "search.hideMatches_other": "Ocultar {count} ocorrências em {path}",
  "search.searchingWeb": "Buscando na web…",
  "search.searching": "Buscando…",
  "search.searchedFor": "Busca por",
  "search.queryIn": "{pattern} em {path}",
  "search.line": "L{line}",
  "search.matches_one": "{count} ocorrência",
  "search.matches_other": "{count} ocorrências",
  "search.dir": "pasta",
};

export const FILES_SEARCH_TEXT_ZH: Record<FilesSearchTextKey, string> = {
  "files.hideTree": "隐藏文件树",
  "files.showTree": "显示文件树",
  "files.toggleTree": "切换文件树",
  "files.filterPlaceholder": "筛选文件...",
  "files.empty": "空",
  "files.noWorkspace": "无工作区",
  "files.noMatches": "无匹配项",
  "files.resizeTree": "调整文件树大小",
  "files.unsavedChanges": "未保存的更改",
  "files.options": "文件选项",
  "files.copyPath": "复制路径",
  "files.copyContents": "复制文件内容",
  "files.wordWrap": "自动换行",
  "files.openContainingFolderMenu": "打开所在文件夹",
  "files.open": "打开",
  "files.openContainingFolder": "打开所在文件夹",
  "files.selectFile": "从工作区文件树中选择一个文件",
  "files.noFileOpen": "未打开文件",
  "files.binaryNoPreview": "二进制文件——无法预览。",
  "files.previewTruncated": "预览已截断",
  "files.workspaceFallback": "工作区",
  "files.keptDraftNotice": "有未保存的更改——该行可能已移动",
  "files.dialogTitle": "保存对 {name} 的更改？",
  "files.dialogDescription": "你有未保存的更改。如果放弃，这些更改将会丢失。",
  "files.save": "保存",
  "files.discard": "放弃",
  "files.cancel": "取消",
  "files.saveFailed": "无法保存：{message}",
  "search.found_one": "找到 {count} 个结果",
  "search.found_other": "找到 {count} 个结果",
  "search.outsideWorkspace": "工作区外",
  "search.outsideTitle": "在工作区外：{path}",
  "search.outsideLabel": "{path}（在工作区外）",
  "search.openAtLine": "在第 {line} 行打开 {path}",
  "search.open": "打开 {path}",
  "search.openMatch": "在第 {line} 行打开 {path}：{text}",
  "search.showMatches_one": "显示 {path} 中的 {count} 处匹配",
  "search.showMatches_other": "显示 {path} 中的 {count} 处匹配",
  "search.hideMatches_one": "隐藏 {path} 中的 {count} 处匹配",
  "search.hideMatches_other": "隐藏 {path} 中的 {count} 处匹配",
  "search.searchingWeb": "正在搜索网络…",
  "search.searching": "正在搜索…",
  "search.searchedFor": "搜索内容",
  "search.queryIn": "{path} 中的 {pattern}",
  "search.line": "第 {line} 行",
  "search.matches_one": "{count} 处匹配",
  "search.matches_other": "{count} 处匹配",
  "search.dir": "目录",
};
