/**
 * Group Room UI copy (C6): every user-visible string of `features/groups/`
 * in en / pt / zh. Keys are `area.name`; plural pairs end in `_one` / `_other`;
 * `{name}` placeholders are filled by `groupText` (group-room-locale.ts).
 * The en table defines the key set; pt and zh must have exactly the same keys
 * (type-checked here, and by the parity test for the placeholder sets).
 *
 * Generated layout: one key per line, same order in the three tables.
 */

const GROUP_TASK_TEXT_EN = {
  "agents.applyTemplateCapabilities": "Apply capabilities from {name}",
  "agents.templateCapabilitiesHint": "Updates this draft's work capabilities only. Save to apply.",
  "agents.capabilitiesUnconfigured":
    "Capabilities are not configured. Choose capabilities and supported task kinds to receive typed tasks.",
  "integration.title": "Integrate task",
  "integration.close": "Close integration",
  "integration.loadingStatus": "Checking integration status…",
  "integration.loadingPreview": "Loading integration preview…",
  "integration.noCommitExplanation":
    "Changes are in the working tree as a no-commit merge. Complete the merge in Git.",
  "integration.conflicts": "Merge conflicts",
  "integration.resolveConflicts": "Resolve or abort this merge conflict",
  "integration.aborting": "Aborting…",
  "integration.abort": "Abort merge",
  "integration.sourceBranch": "Source branch",
  "integration.targetBranch": "Target branch",
  "integration.commits": "Commits",
  "integration.noCommits": "No commits to apply.",
  "integration.commitsOmitted": "{count} more commits omitted.",
  "integration.changedFiles": "Changed files",
  "integration.noChangedFiles": "No changed files.",
  "integration.filesOmitted": "{count} more files omitted.",
  "integration.diffSummary": "Diff summary",
  "integration.noDiffSummary": "No diff summary available.",
  "integration.noChanges": "This preview contains no changes.",
  "integration.refreshPreview": "Refresh preview",
  "integration.requestPreview": "Request a new preview",
  "integration.confirmMerge": "I confirm applying this no-commit merge to the target branch.",
  "integration.applying": "Applying…",
  "integration.applyMerge": "Apply no-commit merge",
  "integration.checkingStatus": "Checking status…",
  "integration.checkStatus": "Check integration status",
  "integration.status.ready": "Preview ready. Confirm before applying.",
  "integration.status.applying": "Applying the confirmed integration…",
  "integration.status.applied": "Applied as a no-commit change in the working tree.",
  "integration.status.conflict": "Integration has conflicts that need resolution.",
  "integration.status.aborted": "The pending merge was aborted.",
  "integration.status.noChanges": "There are no changes to integrate.",
  "proactivity.title": "Proactivity",
  "proactivity.defaultDescription":
    "Suggestions are the default. Limited automatic wakes require opt-in for this group.",
  "proactivity.automaticSuggestions": "Automatic suggestions",
  "proactivity.automate": "Automate",
  "proactivity.suggestions": "Suggestions",
  "proactivity.loading": "Loading suggestions…",
  "proactivity.noPending": "No pending suggestions.",
  "proactivity.source": "Source:",
  "proactivity.delegateTo": "Delegate to",
  "proactivity.destination": "Destination:",
  "proactivity.chooseActiveMember": "Choose an active group member",
  "proactivity.startExecution": "Start new execution",
  "proactivity.accept": "Accept suggestion",
  "proactivity.discard": "Discard suggestion",
  "taskDetails.status.open": "Open",
  "taskDetails.status.inProgress": "In progress",
  "taskDetails.status.blocked": "Blocked",
  "taskDetails.status.inReview": "In review",
  "taskDetails.status.done": "Done",
  "taskDetails.status.cancelled": "Cancelled",
  "taskDetails.notAssigned": "Not assigned",
  "taskDetails.formerMember": "Former member",
  "taskDetails.notSet": "Not set",
  "taskDetails.verification": "Verification",
  "taskDetails.stage.plan": "Plan",
  "taskDetails.stage.implement": "Implement",
  "taskDetails.stage.review": "Review",
  "taskDetails.stage.deliver": "Deliver",
  "taskDetails.outcome.passed": "Passed",
  "taskDetails.outcome.reviewApproved": "Approved by reviewer",
  "taskDetails.outcome.failed": "Failed",
  "taskDetails.outcome.skipped": "Skipped",
  "taskDetails.outcome.stale": "Out of date",
  "taskDetails.outcome.unavailable": "Unavailable",
  "taskDetails.outcome.userConfirmed": "User confirmed (not QA)",
  "taskDetails.outcome.missing": "Missing",
  "taskDetails.aria": "Task details",
  "taskDetails.close": "Close",
  "taskDetails.closeAria": "Close task details",
  "taskDetails.loading": "Loading task details…",
  "taskDetails.prioritySuffix": "{priority} priority",
  "taskDetails.owner": "Owner",
  "taskDetails.reviewer": "Reviewer",
  "taskDetails.dependencies": "Dependencies",
  "taskDetails.criteriaAndQa": "Criteria and QA",
  "taskDetails.sourceUnavailable": "Current source is unavailable.",
  "taskDetails.reviewEvidence": "Review evidence",
  "taskDetails.openQaSession": "Open QA session",
  "taskDetails.review": "Review:",
  "taskDetails.history": "History",
  "taskDetails.title": "Title",
  "taskDetails.description": "Description",
  "taskDetails.kind": "Kind",
  "taskDetails.priority": "Priority",
  "taskDetails.priority.low": "Low",
  "taskDetails.priority.normal": "Normal",
  "taskDetails.priority.high": "High",
  "taskDetails.kind.legacy": "Legacy",
  "taskDetails.kind.code": "Code",
  "taskDetails.kind.docs": "Docs",
  "taskDetails.kind.design": "Design",
  "taskDetails.kind.review": "Review",
  "taskDetails.kind.research": "Research",
  "taskDetails.kind.question": "Question",
  "taskDetails.transition": "{action}: {from} → {to}",
  "taskDetails.omittedDependencies": "{count} more tasks are omitted from this list.",
  "taskDetails.criteria": "Criteria",
  "taskDetails.criterion": "Criterion",
  "taskDetails.check.tests": "tests",
  "taskDetails.check.typecheck": "typecheck",
  "taskDetails.check.lint": "lint",
  "taskDetails.check.build": "build",
  "taskDetails.removeCriterion": "Remove criterion",
  "taskDetails.addCriterion": "Add criterion",
  "taskDetails.newCriterion": "New criterion",
  "taskDetails.verificationPolicy": "Verification policy",
  "taskDetails.mode": "Mode",
  "taskDetails.noRequiredQa": "No required QA",
  "taskDetails.requireQa": "Require QA",
  "taskDetails.requireReviewerApproval": "Require reviewer approval",
  "taskDetails.noReviewer": "No reviewer",
  "taskDetails.discard": "Discard",
  "taskDetails.saving": "Saving…",
  "taskDetails.saveTask": "Save task",
  "taskDetails.editTask": "Edit task",
  "taskDetails.reviewIntegration": "Review integration",
  "taskDetails.details": "Details",
  "error.verification-required": "Complete the task's required verification before closing it.",
  "error.permission-denied": "Allow Git access before applying or aborting this task integration.",
  "error.stale-task": "The task changed. Refresh it and try again.",
  "error.dependency-cycle": "The task dependencies contain a cycle.",
  "error.invalid-dependency": "Choose tasks in this group as dependencies.",
  "error.stale-evidence": "The task evidence is out of date. Run verification again.",
} as const;

const GROUP_TASK_TEXT_PT: Record<keyof typeof GROUP_TASK_TEXT_EN, string> = {
  "agents.applyTemplateCapabilities": "Aplicar capacidades de {name}",
  "agents.templateCapabilitiesHint":
    "Atualiza somente as capacidades de trabalho deste rascunho. Salve para aplicar.",
  "agents.capabilitiesUnconfigured":
    "As capacidades não estão configuradas. Escolha capacidades e tipos de tarefa para receber tarefas tipadas.",
  "integration.title": "Integrar tarefa",
  "integration.close": "Fechar integração",
  "integration.loadingStatus": "Verificando o status da integração…",
  "integration.loadingPreview": "Carregando prévia da integração…",
  "integration.noCommitExplanation":
    "As alterações estão na árvore de trabalho como um merge sem commit. Conclua o merge no Git.",
  "integration.conflicts": "Conflitos de merge",
  "integration.resolveConflicts": "Resolva ou aborte este conflito de merge",
  "integration.aborting": "Abortando…",
  "integration.abort": "Abortar merge",
  "integration.sourceBranch": "Branch de origem",
  "integration.targetBranch": "Branch de destino",
  "integration.commits": "Commits",
  "integration.noCommits": "Nenhum commit para aplicar.",
  "integration.commitsOmitted": "Mais {count} commits omitidos.",
  "integration.changedFiles": "Arquivos alterados",
  "integration.noChangedFiles": "Nenhum arquivo alterado.",
  "integration.filesOmitted": "Mais {count} arquivos omitidos.",
  "integration.diffSummary": "Resumo do diff",
  "integration.noDiffSummary": "Resumo do diff indisponível.",
  "integration.noChanges": "Esta prévia não contém alterações.",
  "integration.refreshPreview": "Atualizar prévia",
  "integration.requestPreview": "Solicitar nova prévia",
  "integration.confirmMerge": "Confirmo aplicar este merge sem commit à branch de destino.",
  "integration.applying": "Aplicando…",
  "integration.applyMerge": "Aplicar merge sem commit",
  "integration.checkingStatus": "Verificando status…",
  "integration.checkStatus": "Verificar status da integração",
  "integration.status.ready": "Prévia pronta. Confirme antes de aplicar.",
  "integration.status.applying": "Aplicando a integração confirmada…",
  "integration.status.applied": "Aplicado como alteração sem commit na árvore de trabalho.",
  "integration.status.conflict": "A integração tem conflitos que precisam ser resolvidos.",
  "integration.status.aborted": "O merge pendente foi abortado.",
  "integration.status.noChanges": "Não há alterações para integrar.",
  "proactivity.title": "Proatividade",
  "proactivity.defaultDescription":
    "Sugestões são o padrão. Despertares automáticos limitados exigem ativação neste grupo.",
  "proactivity.automaticSuggestions": "Sugestões automáticas",
  "proactivity.automate": "Automatizar",
  "proactivity.suggestions": "Sugestões",
  "proactivity.loading": "Carregando sugestões…",
  "proactivity.noPending": "Nenhuma sugestão pendente.",
  "proactivity.source": "Origem:",
  "proactivity.delegateTo": "Delegar para",
  "proactivity.destination": "Destino:",
  "proactivity.chooseActiveMember": "Escolha um membro ativo do grupo",
  "proactivity.startExecution": "Iniciar nova execução",
  "proactivity.accept": "Aceitar sugestão",
  "proactivity.discard": "Descartar sugestão",
  "taskDetails.status.open": "Aberta",
  "taskDetails.status.inProgress": "Em andamento",
  "taskDetails.status.blocked": "Bloqueada",
  "taskDetails.status.inReview": "Em revisão",
  "taskDetails.status.done": "Concluída",
  "taskDetails.status.cancelled": "Cancelada",
  "taskDetails.notAssigned": "Não atribuída",
  "taskDetails.formerMember": "Ex-membro",
  "taskDetails.notSet": "Não definido",
  "taskDetails.verification": "Verificação",
  "taskDetails.stage.plan": "Planejamento",
  "taskDetails.stage.implement": "Implementação",
  "taskDetails.stage.review": "Revisão",
  "taskDetails.stage.deliver": "Entrega",
  "taskDetails.outcome.passed": "Aprovado",
  "taskDetails.outcome.reviewApproved": "Aprovado pelo revisor",
  "taskDetails.outcome.failed": "Falhou",
  "taskDetails.outcome.skipped": "Ignorado",
  "taskDetails.outcome.stale": "Desatualizado",
  "taskDetails.outcome.unavailable": "Indisponível",
  "taskDetails.outcome.userConfirmed": "Confirmado pelo usuário (não é QA)",
  "taskDetails.outcome.missing": "Ausente",
  "taskDetails.aria": "Detalhes da tarefa",
  "taskDetails.close": "Fechar",
  "taskDetails.closeAria": "Fechar detalhes da tarefa",
  "taskDetails.loading": "Carregando detalhes da tarefa…",
  "taskDetails.prioritySuffix": "Prioridade {priority}",
  "taskDetails.owner": "Responsável",
  "taskDetails.reviewer": "Revisor",
  "taskDetails.dependencies": "Dependências",
  "taskDetails.criteriaAndQa": "Critérios e QA",
  "taskDetails.sourceUnavailable": "A origem atual está indisponível.",
  "taskDetails.reviewEvidence": "Evidência de revisão",
  "taskDetails.openQaSession": "Abrir sessão de QA",
  "taskDetails.review": "Revisão:",
  "taskDetails.history": "Histórico",
  "taskDetails.title": "Título",
  "taskDetails.description": "Descrição",
  "taskDetails.kind": "Tipo",
  "taskDetails.priority": "Prioridade",
  "taskDetails.priority.low": "Baixa",
  "taskDetails.priority.normal": "Normal",
  "taskDetails.priority.high": "Alta",
  "taskDetails.kind.legacy": "Legada",
  "taskDetails.kind.code": "Código",
  "taskDetails.kind.docs": "Documentação",
  "taskDetails.kind.design": "Design",
  "taskDetails.kind.review": "Revisão",
  "taskDetails.kind.research": "Pesquisa",
  "taskDetails.kind.question": "Pergunta",
  "taskDetails.transition": "{action}: {from} → {to}",
  "taskDetails.omittedDependencies": "Mais {count} tarefas omitidas desta lista.",
  "taskDetails.criteria": "Critérios",
  "taskDetails.criterion": "Critério",
  "taskDetails.check.tests": "Testes",
  "taskDetails.check.typecheck": "Verificação de tipos",
  "taskDetails.check.lint": "Verificação estática",
  "taskDetails.check.build": "Build",
  "taskDetails.removeCriterion": "Remover critério",
  "taskDetails.addCriterion": "Adicionar critério",
  "taskDetails.newCriterion": "Novo critério",
  "taskDetails.verificationPolicy": "Política de verificação",
  "taskDetails.mode": "Modo",
  "taskDetails.noRequiredQa": "QA não obrigatório",
  "taskDetails.requireQa": "Exigir QA",
  "taskDetails.requireReviewerApproval": "Exigir aprovação do revisor",
  "taskDetails.noReviewer": "Sem revisor",
  "taskDetails.discard": "Descartar",
  "taskDetails.saving": "Salvando…",
  "taskDetails.saveTask": "Salvar tarefa",
  "taskDetails.editTask": "Editar tarefa",
  "taskDetails.reviewIntegration": "Revisar integração",
  "taskDetails.details": "Detalhes",
  "error.verification-required": "Conclua a verificação obrigatória da tarefa antes de encerrá-la.",
  "error.permission-denied": "Permita o acesso ao Git antes de aplicar ou abortar esta integração.",
  "error.stale-task": "A tarefa mudou. Atualize e tente novamente.",
  "error.dependency-cycle": "As dependências da tarefa contêm um ciclo.",
  "error.invalid-dependency": "Escolha tarefas deste grupo como dependências.",
  "error.stale-evidence":
    "A evidência da tarefa está desatualizada. Execute a verificação novamente.",
};

const GROUP_TASK_TEXT_ZH: Record<keyof typeof GROUP_TASK_TEXT_EN, string> = {
  "agents.applyTemplateCapabilities": "应用 {name} 的能力配置",
  "agents.templateCapabilitiesHint": "仅更新此草稿的工作能力。保存后生效。",
  "agents.capabilitiesUnconfigured": "尚未配置能力。请选择能力和支持的任务类型，以接收结构化任务。",
  "integration.title": "集成任务",
  "integration.close": "关闭集成窗口",
  "integration.loadingStatus": "正在检查集成状态…",
  "integration.loadingPreview": "正在加载集成预览…",
  "integration.noCommitExplanation": "更改已作为无提交合并保留在工作树中。请在 Git 中完成合并。",
  "integration.conflicts": "合并冲突",
  "integration.resolveConflicts": "解决或中止此合并冲突",
  "integration.aborting": "正在中止…",
  "integration.abort": "中止合并",
  "integration.sourceBranch": "源分支",
  "integration.targetBranch": "目标分支",
  "integration.commits": "提交",
  "integration.noCommits": "没有可应用的提交。",
  "integration.commitsOmitted": "另有 {count} 个提交未显示。",
  "integration.changedFiles": "已更改文件",
  "integration.noChangedFiles": "没有更改的文件。",
  "integration.filesOmitted": "另有 {count} 个文件未显示。",
  "integration.diffSummary": "差异摘要",
  "integration.noDiffSummary": "差异摘要不可用。",
  "integration.noChanges": "此预览不包含任何更改。",
  "integration.refreshPreview": "刷新预览",
  "integration.requestPreview": "请求新预览",
  "integration.confirmMerge": "我确认将此无提交合并应用到目标分支。",
  "integration.applying": "正在应用…",
  "integration.applyMerge": "应用无提交合并",
  "integration.checkingStatus": "正在检查状态…",
  "integration.checkStatus": "检查集成状态",
  "integration.status.ready": "预览已就绪。应用前请确认。",
  "integration.status.applying": "正在应用已确认的集成…",
  "integration.status.applied": "已作为无提交更改应用到工作树。",
  "integration.status.conflict": "集成存在需要解决的冲突。",
  "integration.status.aborted": "已中止待处理的合并。",
  "integration.status.noChanges": "没有要集成的更改。",
  "proactivity.title": "主动协作",
  "proactivity.defaultDescription": "默认提供建议。此群组需选择加入才会启用有限的自动唤醒。",
  "proactivity.automaticSuggestions": "自动建议",
  "proactivity.automate": "自动执行",
  "proactivity.suggestions": "建议",
  "proactivity.loading": "正在加载建议…",
  "proactivity.noPending": "没有待处理的建议。",
  "proactivity.source": "来源：",
  "proactivity.delegateTo": "委派给",
  "proactivity.destination": "目标：",
  "proactivity.chooseActiveMember": "选择群组中的活跃成员",
  "proactivity.startExecution": "开始新执行",
  "proactivity.accept": "接受建议",
  "proactivity.discard": "舍弃建议",
  "taskDetails.status.open": "待处理",
  "taskDetails.status.inProgress": "进行中",
  "taskDetails.status.blocked": "受阻",
  "taskDetails.status.inReview": "审核中",
  "taskDetails.status.done": "已完成",
  "taskDetails.status.cancelled": "已取消",
  "taskDetails.notAssigned": "未分配",
  "taskDetails.formerMember": "前成员",
  "taskDetails.notSet": "未设置",
  "taskDetails.verification": "验证",
  "taskDetails.stage.plan": "计划",
  "taskDetails.stage.implement": "实施",
  "taskDetails.stage.review": "审核",
  "taskDetails.stage.deliver": "交付",
  "taskDetails.outcome.passed": "通过",
  "taskDetails.outcome.reviewApproved": "审核人已批准",
  "taskDetails.outcome.failed": "失败",
  "taskDetails.outcome.skipped": "已跳过",
  "taskDetails.outcome.stale": "已过期",
  "taskDetails.outcome.unavailable": "不可用",
  "taskDetails.outcome.userConfirmed": "用户已确认（非 QA）",
  "taskDetails.outcome.missing": "缺失",
  "taskDetails.aria": "任务详情",
  "taskDetails.close": "关闭",
  "taskDetails.closeAria": "关闭任务详情",
  "taskDetails.loading": "正在加载任务详情…",
  "taskDetails.prioritySuffix": "{priority}优先级",
  "taskDetails.owner": "负责人",
  "taskDetails.reviewer": "审核人",
  "taskDetails.dependencies": "依赖项",
  "taskDetails.criteriaAndQa": "验收标准与 QA",
  "taskDetails.sourceUnavailable": "当前来源不可用。",
  "taskDetails.reviewEvidence": "审核证据",
  "taskDetails.openQaSession": "打开 QA 会话",
  "taskDetails.review": "审核：",
  "taskDetails.history": "历史记录",
  "taskDetails.title": "标题",
  "taskDetails.description": "描述",
  "taskDetails.kind": "类型",
  "taskDetails.priority": "优先级",
  "taskDetails.priority.low": "低",
  "taskDetails.priority.normal": "普通",
  "taskDetails.priority.high": "高",
  "taskDetails.kind.legacy": "旧版",
  "taskDetails.kind.code": "代码",
  "taskDetails.kind.docs": "文档",
  "taskDetails.kind.design": "设计",
  "taskDetails.kind.review": "审核",
  "taskDetails.kind.research": "研究",
  "taskDetails.kind.question": "问题",
  "taskDetails.transition": "{action}：{from} → {to}",
  "taskDetails.omittedDependencies": "列表中另有 {count} 个任务未显示。",
  "taskDetails.criteria": "验收标准",
  "taskDetails.criterion": "标准",
  "taskDetails.check.tests": "测试",
  "taskDetails.check.typecheck": "类型检查",
  "taskDetails.check.lint": "代码风格检查",
  "taskDetails.check.build": "构建",
  "taskDetails.removeCriterion": "移除标准",
  "taskDetails.addCriterion": "添加标准",
  "taskDetails.newCriterion": "新标准",
  "taskDetails.verificationPolicy": "验证策略",
  "taskDetails.mode": "模式",
  "taskDetails.noRequiredQa": "无需 QA",
  "taskDetails.requireQa": "需要 QA",
  "taskDetails.requireReviewerApproval": "需要审核人批准",
  "taskDetails.noReviewer": "无审核人",
  "taskDetails.discard": "放弃",
  "taskDetails.saving": "正在保存…",
  "taskDetails.saveTask": "保存任务",
  "taskDetails.editTask": "编辑任务",
  "taskDetails.reviewIntegration": "查看集成",
  "taskDetails.details": "详情",
  "error.verification-required": "关闭任务前，请完成其必需的验证。",
  "error.permission-denied": "应用或中止此任务集成前，请允许访问 Git。",
  "error.stale-task": "任务已更改。请刷新后重试。",
  "error.dependency-cycle": "任务依赖关系中存在循环。",
  "error.invalid-dependency": "请选择此群组中的任务作为依赖项。",
  "error.stale-evidence": "任务证据已过期。请重新运行验证。",
};

export const GROUP_ROOM_TEXT_EN = {
  "common.cancel": "Cancel",
  "common.remove": "Remove {name}",
  "common.noModelConfigured": "No model configured",
  "common.lead": "Lead",
  "room.hideActivity": "Hide activity",
  "room.showActivity": "Show activity",
  "room.chooseFolder": "Choose folder",
  "room.addAgent": "Add agent",
  "blocked.projectRequired": "Choose a folder to continue this group",
  "blocked.minMembers": "Add a member to continue",
  "header.stageTitle": "Collaboration stage (from the room transcript)",
  "header.owner": "Owner:",
  "header.stage": "Stage · {stage}",
  "stage.Handoff": "Handoff",
  "stage.Review": "Review",
  "stage.Agree": "Agree",
  "stage.Ready": "Ready",
  "header.noProject": "No project",
  "header.search": "Search in conversation",
  "header.clearSearch": "Clear search",
  "header.stopTitle": "End the chain and stop running member turns",
  "header.stop": "Stop",
  "header.groupActions": "Group actions",
  "header.moreAgents": "{count} more agents: {names}",
  "popover.edit": "Edit {name}",
  "popover.editShort": "Edit",
  "popover.agentPresence": "Agent presence",
  "popover.profileUnavailable": "{name} profile unavailable. {presence}",
  "project.contextTitle": "Shared project map for this group's Project",
  "project.mapping": "Mapping project…",
  "project.ready": "Project context · Ready",
  "project.updating": "Project context · Updating",
  "project.needsRefresh": "Project context · Needs refresh",
  "composer.updatePausedTitle": "Paused while Modus updates",
  "composer.updatePausedBody":
    "Messages are saved. Pending tasks resume after restart. Interrupted runs stay visible for you to resume.",
  "composer.replying": "Replying",
  "composer.kickoffTitle": "Kick off the group",
  "composer.kickoffHint": "Outcome + first owner — the room stays the source of truth.",
  "composer.kickoffOutcome": "Outcome",
  "composer.kickoffOutcomePlaceholder": "What should the group deliver?",
  "composer.kickoffFirstOwner": "First owner",
  "composer.kickoffInsert": "Insert kickoff",
  "composer.inputLabel": "Message the group",
  "composer.placeholder": "Message the group, @ to mention, attach files",
  "composer.attachFiles": "Attach files",
  "composer.executionMode": "Execution mode",
  "composer.newTask": "New task",
  "composer.complement": "Follow-up",
  "composer.send": "Send",
  "attachments.readFailed": "Failed to read file.",
  "attachments.imageTooLarge": "Image too large (max {max} MB)",
  "attachments.imageUnreadable": "Could not read image",
  "attachments.fileTooLarge": "File too large (max {max} MB)",
  "attachments.pathUnavailable": "File path unavailable",
  "row.filterExecution": "Filter conversation to this execution",
  "row.tokensTitle": "Estimated tokens for this execution (characters ÷ 4)",
  "row.tokens": "~{count} tokens",
  "row.copyMessage": "Copy message",
  "row.replyToMessage": "Reply to message",
  "row.reply": "Reply",
  "row.you": "You",
  "row.member": "Member",
  "row.message": "Message",
  "row.replyingTo": "Replying to {name}",
  "row.attachment": "Attachment",
  "row.earlierMessage": "Earlier message",
  "row.youInitial": "Y",
  "row.human": "Human",
  "row.agent": "Agent",
  "status.turnFailed": "Turn failed",
  "status.turnStopped": "Turn stopped",
  "status.stoppedByYou": "Stopped by you",
  "status.noNextOwner": "No next owner — @mention someone or propose agreement",
  "status.worktreeReady": "Worktree ready: `{branch}`",
  "status.archived": "{name} is archived",
  "status.limitAgentMessages":
    "Automatic handoffs paused: this chain reached its limit of {count} agent messages. Already queued turns will finish.",
  "status.limitMemberWakes":
    "Automatic handoffs paused: a member was already woken {count} times in this chain. Already queued turns will finish.",
  "status.limitInputTokens":
    "Automatic handoffs paused: this chain used its estimated {count}k-token budget of group prompts. Already queued turns will finish.",
  "status.limitContext":
    "Automatic handoffs paused: the message does not fit the estimated {count}k-token group context of a turn. Already queued turns will finish.",
  "collab.handoffDefault": "@{name}, please take this from here.",
  "collab.blocked": "Blocked",
  "collab.blockedWith": "Blocked — {text}",
  "collab.proposed": "Proposed",
  "collab.proposedWith": "Proposed — {text}",
  "collab.agreed": "Agreed",
  "collab.agreedWith": "Agreed — {text}",
  "activity.title": "Activity",
  "activity.tokens": "Tokens",
  "activity.tokensSummary_one": "Estimated · ~{total} across {count} execution",
  "activity.tokensSummary_other": "Estimated · ~{total} across {count} executions",
  "activity.buttonActive": "Activity ({count} active)",
  "activity.live": "Live",
  "activity.details": "Details",
  "activity.coordination": "Coordination",
  "activity.noHandoff": "No active handoff",
  "activity.coordinatorOn": "Coordinator on",
  "activity.freeCollab": "Free collaboration",
  "activity.turnOffCoordinator": "Turn off Coordinator mode",
  "activity.leadCoordinates": "Lead coordinates untargeted messages",
  "activity.addLeadForCoordinator": "Add a Lead to enable Coordinator mode",
  "activity.disable": "Disable",
  "activity.enable": "Enable",
  "list.empty": "Write to the group. Members pick up what fits — or @mention someone.",
  "list.thisExecution": "This execution",
  "list.showAll": "Show all",
  "list.loadingOlder": "Loading older messages…",
  "list.noMatches": "No messages match “{query}”.",
  "list.newMessages_one": "{count} new message",
  "list.newMessages_other": "{count} new messages",
  "day.today": "Today",
  "day.yesterday": "Yesterday",
  "decisions.title": "Decisions",
  "decisions.empty": "No decisions yet",
  "decisions.confirmDelete": "Click again to delete",
  "decisions.formerMember": "Former member",
  "decisions.delete": "Delete",
  "result.outcome": "Outcome",
  "result.validations": "Validations",
  "result.changedFiles": "Changed files",
  "result.openItems": "Open items",
  "live.progress": "Progress",
  "kit.completed": "Completed",
  "kit.error": "Error",
  "kit.ready": "Ready",
  "kit.running": "Running",
  "kit.steps": "Steps",
  "kit.image": "Image",
  "kit.text": "Text",
  "kit.file": "File",
  "tasks.confirmCancel": "Click again to cancel",
  "tasks.inProgress": "In progress",
  "tasks.inReview": "In review",
  "tasks.blocked": "Blocked",
  "tasks.open": "Open",
  "tasks.empty": "No tasks yet. Members create them as they work.",
  "tasks.checklist": "Checklist",
  "tasks.progress": "{done}/{total} done",
  "tasks.hideCancelled": "Hide cancelled",
  "tasks.showCancelled": "Show cancelled ({count})",
  "tasks.done": "Done",
  "tasks.notDone": "Not done",
  "tasks.unassigned": "Unassigned",
  "tasks.cancel": "Cancel task",
  "delivery.delivered": "Delivered",
  "delivery.working": "Working",
  "delivery.noReply": "No reply",
  "delivery.answered": "Answered",
  "manage.title": "Manage members",
  "manage.unknownProject": "Unknown project",
  "manage.noFolder": "No folder",
  "manage.modelRequired": "Choose a model for the new agents.",
  "manage.agents": "Agents",
  "manage.removeTitle": "Removing a member deletes its agent",
  "manage.agentName": "Agent {index} name",
  "manage.agentRole": "Agent {index} role",
  "manage.namePlaceholder": "Name",
  "manage.rolePlaceholder": "Role (optional)",
  "manage.removeAgent": "Remove agent {index}",
  "manage.modelForNew": "Model for new agents",
  "manage.noLead": "No lead",
  "manage.saving": "Saving…",
  "manage.save": "Save members",
  "newGroup.title": "New group",
  "newGroup.description": "Agents that work together in one folder.",
  "newGroup.tabTemplates": "Templates",
  "newGroup.tabCopy": "Copy from another group",
  "newGroup.tabCustom": "New agent",
  "newGroup.sourceTemplate": "Template",
  "newGroup.sourceCopy": "Copy",
  "newGroup.sourceCustom": "Custom",
  "newGroup.folder": "Folder",
  "newGroup.chooseFolder": "Choose a folder",
  "newGroup.addFolder": "Add folder…",
  "newGroup.name": "Name",
  "newGroup.collabPipeline": "Collab pipeline · Planner → Builder → Reviewer",
  "newGroup.suggestedLead": "Suggested lead",
  "newGroup.customizeLabel": "Customize {name}",
  "newGroup.customize": "Customize",
  "newGroup.addLabel": "Add {name}",
  "newGroup.add": "Add",
  "newGroup.copyHint":
    "Adds an independent copy: same name, role, instructions, model and look, no history. Editing it never changes the original.",
  "newGroup.loadingAgents": "Loading agents…",
  "newGroup.noCopyable": "No agents in other groups yet.",
  "newGroup.copyLabel": "Copy {name} from {group}",
  "newGroup.copy": "Copy",
  "newGroup.customHint":
    "A custom agent needs a name and a model. Leave the role and instructions empty to generate them: the roles already chosen here are sent, so the new one complements them.",
  "newGroup.newAgent": "New agent…",
  "newGroup.members": "Members",
  "newGroup.addAtLeast": "Add at least {count} agents.",
  "newGroup.memberFallback": "member {index}",
  "newGroup.memberName": "Name of member {index}",
  "newGroup.isLead": "{name} is the lead",
  "newGroup.makeLeadLabel": "Make {name} lead",
  "newGroup.leadClear": "Lead (click to clear)",
  "newGroup.makeLead": "Make lead",
  "newGroup.noRole": "No role",
  "newGroup.modelOf": "Model of {name}",
  "newGroup.chooseModel": "Choose a model",
  "newGroup.creating": "Creating…",
  "newGroup.create": "Create",
  "hint.folder": "Choose a folder for the group.",
  "hint.min": "A group needs at least {count} agents.",
  "hint.max": "A group can have at most {count} agents.",
  "hint.names": "Each agent needs a different name.",
  "hint.emptyName": "Every agent needs a name.",
  "hint.model": "Choose a model for every agent that isn't from a template.",
  "sidebar.removeProjectGroups_one": "This also deletes 1 group, its agents and chats: {names}",
  "sidebar.removeProjectGroups_other":
    "This also deletes {count} groups, their agents and chats: {names}",
  "sidebar.deleteGroup_one": "This deletes its 1 agent, their chats and all group messages",
  "sidebar.deleteGroup_other":
    "This deletes its {count} agents, their chats and all group messages",
  "error.group-not-found": "This group no longer exists.",
  "error.workspace-not-found": "The selected project no longer exists.",
  "error.session-not-found": "One of the selected chats no longer exists.",
  "error.message-not-found": "That message isn't part of this group.",
  "error.task-not-found": "That task no longer exists.",
  "error.decision-not-found": "That decision no longer exists.",
  "error.workspace-mismatch":
    "Every member must belong to the group's project (or have no folder when the group has no project).",
  "error.already-in-group": "One of the selected chats is already in another group.",
  "error.subagent-session": "Subagent chats can't join a group.",
  "error.archived-session": "Archived chats can't join a group. Restore the chat first.",
  "error.not-a-member": "That chat isn't a member of this group.",
  "error.invalid-value": "Some of the group details are invalid.",
  "error.not-owner": "Only the task's owner can do that.",
  "error.not-reviewer": "Only the task's reviewer can do that.",
  "error.task-taken": "That task already has an owner.",
  "error.invalid-transition": "That task can't move to that status from where it is.",
  "error.self-review": "A task's owner can't review their own task.",
  "error.ambiguous-member": "More than one member has that name. Pick the chat by its id.",
  "error.no-git-project": "Member worktrees need the group's Project to be a Git repository.",
  "error.branch-checked-out":
    "The member's branch is checked out in another folder. Switch that checkout to another branch first.",
  "error.call-alone":
    "The member must start its worktree with a message that makes no other tool call.",
  "error.invalid-text": "A decision needs 1 to 500 characters of text.",
  "error.limit-reached": "This group already has 100 decisions. Delete one first.",
  "error.not-coordinator": "Only the group's Lead can assign tasks.",
  "error.coordinator-off": "Coordinator mode is off, or the group has no Lead.",
  "error.agent-not-found": "That agent no longer exists.",
  "error.agent-name-taken": "Another agent already has that name.",
  "error.group-project-required": "Choose a folder to continue this group.",
  "error.member-archived": "That agent is archived. Restore it first.",
  "error.group-min-members": "A group needs at least 2 agents.",
  "error.group-max-members": "A group can have at most 10 agents.",
  "error.agent-model-required": "Choose a model for this agent.",
  "error.agent-model-unavailable":
    "That model is not available. Connect its provider or choose another.",
  "error.agent-avatar-shape-taken": "Another agent in this group already uses that shape.",
  ...GROUP_TASK_TEXT_EN,
} as const;

export type GroupTextKey = keyof typeof GROUP_ROOM_TEXT_EN;

export const GROUP_ROOM_TEXT_PT: Record<GroupTextKey, string> = {
  "common.cancel": "Cancelar",
  "common.remove": "Remover {name}",
  "common.noModelConfigured": "Nenhum modelo configurado",
  "common.lead": "Lead",
  "room.hideActivity": "Ocultar atividade",
  "room.showActivity": "Mostrar atividade",
  "room.chooseFolder": "Escolher pasta",
  "room.addAgent": "Adicionar agente",
  "blocked.projectRequired": "Escolha uma pasta para continuar este grupo",
  "blocked.minMembers": "Adicione um membro para continuar",
  "header.stageTitle": "Etapa da colaboração (a partir da conversa da sala)",
  "header.owner": "Responsável:",
  "header.stage": "Etapa · {stage}",
  "stage.Handoff": "Passagem",
  "stage.Review": "Revisão",
  "stage.Agree": "Acordo",
  "stage.Ready": "Pronto",
  "header.noProject": "Sem projeto",
  "header.search": "Buscar na conversa",
  "header.clearSearch": "Limpar busca",
  "header.stopTitle": "Encerrar a cadeia e parar os turnos em andamento",
  "header.stop": "Parar",
  "header.groupActions": "Ações do grupo",
  "header.moreAgents": "Mais {count} agentes: {names}",
  "popover.edit": "Editar {name}",
  "popover.editShort": "Editar",
  "popover.agentPresence": "Presença dos agentes",
  "popover.profileUnavailable": "Perfil de {name} indisponível. {presence}",
  "project.contextTitle": "Mapa compartilhado do projeto deste grupo",
  "project.mapping": "Mapeando o projeto…",
  "project.ready": "Contexto do projeto · Pronto",
  "project.updating": "Contexto do projeto · Atualizando",
  "project.needsRefresh": "Contexto do projeto · Precisa atualizar",
  "composer.updatePausedTitle": "Pausado enquanto o Modus atualiza",
  "composer.updatePausedBody":
    "As mensagens ficam salvas. Tarefas pendentes continuam depois de reiniciar. Execuções interrompidas continuam visíveis para você retomar.",
  "composer.replying": "Respondendo",
  "composer.kickoffTitle": "Iniciar o grupo",
  "composer.kickoffHint":
    "Resultado + primeiro responsável — a sala continua sendo a fonte da verdade.",
  "composer.kickoffOutcome": "Resultado",
  "composer.kickoffOutcomePlaceholder": "O que o grupo deve entregar?",
  "composer.kickoffFirstOwner": "Primeiro responsável",
  "composer.kickoffInsert": "Inserir abertura",
  "composer.inputLabel": "Mensagem para o grupo",
  "composer.placeholder": "Mensagem para o grupo, @ para mencionar, anexe arquivos",
  "composer.attachFiles": "Anexar arquivos",
  "composer.executionMode": "Modo de execução",
  "composer.newTask": "Nova tarefa",
  "composer.complement": "Complementar",
  "composer.send": "Enviar",
  "attachments.readFailed": "Não foi possível ler o arquivo.",
  "attachments.imageTooLarge": "Imagem grande demais (máx. {max} MB)",
  "attachments.imageUnreadable": "Não foi possível ler a imagem",
  "attachments.fileTooLarge": "Arquivo grande demais (máx. {max} MB)",
  "attachments.pathUnavailable": "Caminho do arquivo indisponível",
  "row.filterExecution": "Filtrar a conversa por esta execução",
  "row.tokensTitle": "Tokens estimados desta execução (caracteres ÷ 4)",
  "row.tokens": "~{count} tokens",
  "row.copyMessage": "Copiar mensagem",
  "row.replyToMessage": "Responder à mensagem",
  "row.reply": "Responder",
  "row.you": "Você",
  "row.member": "Membro",
  "row.message": "Mensagem",
  "row.replyingTo": "Respondendo a {name}",
  "row.attachment": "Anexo",
  "row.earlierMessage": "Mensagem anterior",
  "row.youInitial": "V",
  "row.human": "Humano",
  "row.agent": "Agente",
  "status.turnFailed": "Turno falhou",
  "status.turnStopped": "Turno interrompido",
  "status.stoppedByYou": "Interrompido por você",
  "status.noNextOwner": "Sem próximo responsável — @mencione alguém ou proponha um acordo",
  "status.worktreeReady": "Worktree pronta: `{branch}`",
  "status.archived": "{name} está arquivado",
  "status.limitAgentMessages":
    "Passagens automáticas pausadas: esta cadeia atingiu o limite de {count} mensagens de agentes. Os turnos já na fila vão terminar.",
  "status.limitMemberWakes":
    "Passagens automáticas pausadas: um membro já foi acordado {count} vezes nesta cadeia. Os turnos já na fila vão terminar.",
  "status.limitInputTokens":
    "Passagens automáticas pausadas: esta cadeia usou o orçamento estimado de {count} mil tokens de prompts do grupo. Os turnos já na fila vão terminar.",
  "status.limitContext":
    "Passagens automáticas pausadas: a mensagem não cabe no contexto estimado de {count} mil tokens de um turno do grupo. Os turnos já na fila vão terminar.",
  "collab.handoffDefault": "@{name}, por favor assuma daqui.",
  "collab.blocked": "Bloqueado",
  "collab.blockedWith": "Bloqueado — {text}",
  "collab.proposed": "Proposto",
  "collab.proposedWith": "Proposto — {text}",
  "collab.agreed": "Acordado",
  "collab.agreedWith": "Acordado — {text}",
  "activity.title": "Atividade",
  "activity.tokens": "Tokens",
  "activity.tokensSummary_one": "Estimativa · ~{total} em {count} execução",
  "activity.tokensSummary_other": "Estimativa · ~{total} em {count} execuções",
  "activity.buttonActive": "Atividade ({count} ativas)",
  "activity.live": "Ao vivo",
  "activity.details": "Detalhes",
  "activity.coordination": "Coordenação",
  "activity.noHandoff": "Nenhuma passagem ativa",
  "activity.coordinatorOn": "Coordenador ativo",
  "activity.freeCollab": "Colaboração livre",
  "activity.turnOffCoordinator": "Desativar o modo coordenador",
  "activity.leadCoordinates": "O Lead coordena mensagens sem destinatário",
  "activity.addLeadForCoordinator": "Adicione um Lead para ativar o modo coordenador",
  "activity.disable": "Desativar",
  "activity.enable": "Ativar",
  "list.empty": "Escreva para o grupo. Os membros pegam o que se encaixa — ou @mencione alguém.",
  "list.thisExecution": "Esta execução",
  "list.showAll": "Mostrar tudo",
  "list.loadingOlder": "Carregando mensagens anteriores…",
  "list.noMatches": "Nenhuma mensagem corresponde a “{query}”.",
  "list.newMessages_one": "{count} nova mensagem",
  "list.newMessages_other": "{count} novas mensagens",
  "day.today": "Hoje",
  "day.yesterday": "Ontem",
  "decisions.title": "Decisões",
  "decisions.empty": "Nenhuma decisão ainda",
  "decisions.confirmDelete": "Clique de novo para excluir",
  "decisions.formerMember": "Ex-membro",
  "decisions.delete": "Excluir",
  "result.outcome": "Resultado",
  "result.validations": "Validações",
  "result.changedFiles": "Arquivos alterados",
  "result.openItems": "Pendências",
  "live.progress": "Progresso",
  "kit.completed": "Concluído",
  "kit.error": "Erro",
  "kit.ready": "Pronto",
  "kit.running": "Em execução",
  "kit.steps": "Etapas",
  "kit.image": "Imagem",
  "kit.text": "Texto",
  "kit.file": "Arquivo",
  "tasks.confirmCancel": "Clique de novo para cancelar",
  "tasks.inProgress": "Em andamento",
  "tasks.inReview": "Em revisão",
  "tasks.blocked": "Bloqueada",
  "tasks.open": "Aberta",
  "tasks.empty": "Nenhuma tarefa ainda. Os membros criam tarefas enquanto trabalham.",
  "tasks.checklist": "Checklist",
  "tasks.progress": "{done}/{total} concluídas",
  "tasks.hideCancelled": "Ocultar canceladas",
  "tasks.showCancelled": "Mostrar canceladas ({count})",
  "tasks.done": "Concluída",
  "tasks.notDone": "Não concluída",
  "tasks.unassigned": "Sem responsável",
  "tasks.cancel": "Cancelar tarefa",
  "delivery.delivered": "Entregue",
  "delivery.working": "Trabalhando",
  "delivery.noReply": "Sem resposta",
  "delivery.answered": "Respondida",
  "manage.title": "Gerenciar membros",
  "manage.unknownProject": "Projeto desconhecido",
  "manage.noFolder": "Sem pasta",
  "manage.modelRequired": "Escolha um modelo para os novos agentes.",
  "manage.agents": "Agentes",
  "manage.removeTitle": "Remover um membro exclui o agente dele",
  "manage.agentName": "Nome do agente {index}",
  "manage.agentRole": "Função do agente {index}",
  "manage.namePlaceholder": "Nome",
  "manage.rolePlaceholder": "Função (opcional)",
  "manage.removeAgent": "Remover agente {index}",
  "manage.modelForNew": "Modelo para os novos agentes",
  "manage.noLead": "Sem lead",
  "manage.saving": "Salvando…",
  "manage.save": "Salvar membros",
  "newGroup.title": "Novo grupo",
  "newGroup.description": "Agentes que trabalham juntos em uma pasta.",
  "newGroup.tabTemplates": "Templates",
  "newGroup.tabCopy": "Copiar de outro grupo",
  "newGroup.tabCustom": "Novo agente",
  "newGroup.sourceTemplate": "Template",
  "newGroup.sourceCopy": "Cópia",
  "newGroup.sourceCustom": "Personalizado",
  "newGroup.folder": "Pasta",
  "newGroup.chooseFolder": "Escolha uma pasta",
  "newGroup.addFolder": "Adicionar pasta…",
  "newGroup.name": "Nome",
  "newGroup.collabPipeline": "Pipeline colaborativo · Planner → Builder → Reviewer",
  "newGroup.suggestedLead": "Lead sugerido",
  "newGroup.customizeLabel": "Personalizar {name}",
  "newGroup.customize": "Personalizar",
  "newGroup.addLabel": "Adicionar {name}",
  "newGroup.add": "Adicionar",
  "newGroup.copyHint":
    "Adiciona uma cópia independente: mesmo nome, função, instruções, modelo e aparência, sem histórico. Editá-la nunca altera o original.",
  "newGroup.loadingAgents": "Carregando agentes…",
  "newGroup.noCopyable": "Ainda não há agentes em outros grupos.",
  "newGroup.copyLabel": "Copiar {name} de {group}",
  "newGroup.copy": "Copiar",
  "newGroup.customHint":
    "Um agente personalizado precisa de um nome e de um modelo. Deixe a função e as instruções vazias para gerá-las: as funções já escolhidas aqui são enviadas, para que o novo agente as complemente.",
  "newGroup.newAgent": "Novo agente…",
  "newGroup.members": "Membros",
  "newGroup.addAtLeast": "Adicione pelo menos {count} agentes.",
  "newGroup.memberFallback": "membro {index}",
  "newGroup.memberName": "Nome do membro {index}",
  "newGroup.isLead": "{name} é o lead",
  "newGroup.makeLeadLabel": "Tornar {name} lead",
  "newGroup.leadClear": "Lead (clique para remover)",
  "newGroup.makeLead": "Tornar lead",
  "newGroup.noRole": "Sem função",
  "newGroup.modelOf": "Modelo de {name}",
  "newGroup.chooseModel": "Escolha um modelo",
  "newGroup.creating": "Criando…",
  "newGroup.create": "Criar",
  "hint.folder": "Escolha uma pasta para o grupo.",
  "hint.min": "Um grupo precisa de pelo menos {count} agentes.",
  "hint.max": "Um grupo pode ter no máximo {count} agentes.",
  "hint.names": "Cada agente precisa de um nome diferente.",
  "hint.emptyName": "Todo agente precisa de um nome.",
  "hint.model": "Escolha um modelo para cada agente que não veio de um template.",
  "sidebar.removeProjectGroups_one": "Isso também exclui 1 grupo, seus agentes e chats: {names}",
  "sidebar.removeProjectGroups_other":
    "Isso também exclui {count} grupos, seus agentes e chats: {names}",
  "sidebar.deleteGroup_one":
    "Isso exclui o 1 agente do grupo, os chats dele e todas as mensagens do grupo",
  "sidebar.deleteGroup_other":
    "Isso exclui os {count} agentes do grupo, os chats deles e todas as mensagens do grupo",
  "error.group-not-found": "Este grupo não existe mais.",
  "error.workspace-not-found": "O projeto selecionado não existe mais.",
  "error.session-not-found": "Um dos chats selecionados não existe mais.",
  "error.message-not-found": "Essa mensagem não faz parte deste grupo.",
  "error.task-not-found": "Essa tarefa não existe mais.",
  "error.decision-not-found": "Essa decisão não existe mais.",
  "error.workspace-mismatch":
    "Todo membro precisa pertencer ao projeto do grupo (ou não ter pasta quando o grupo não tem projeto).",
  "error.already-in-group": "Um dos chats selecionados já está em outro grupo.",
  "error.subagent-session": "Chats de subagentes não podem entrar em um grupo.",
  "error.archived-session":
    "Chats arquivados não podem entrar em um grupo. Restaure o chat primeiro.",
  "error.not-a-member": "Esse chat não é membro deste grupo.",
  "error.invalid-value": "Alguns dados do grupo são inválidos.",
  "error.not-owner": "Só o responsável pela tarefa pode fazer isso.",
  "error.not-reviewer": "Só o revisor da tarefa pode fazer isso.",
  "error.task-taken": "Essa tarefa já tem um responsável.",
  "error.invalid-transition": "Essa tarefa não pode ir para esse status a partir do atual.",
  "error.self-review": "O responsável por uma tarefa não pode revisar a própria tarefa.",
  "error.ambiguous-member": "Mais de um membro tem esse nome. Escolha o chat pelo id.",
  "error.no-git-project":
    "As worktrees dos membros exigem que o projeto do grupo seja um repositório Git.",
  "error.branch-checked-out":
    "A branch do membro está em checkout em outra pasta. Troque esse checkout para outra branch primeiro.",
  "error.call-alone":
    "O membro precisa iniciar a worktree com uma mensagem que não faça nenhuma outra chamada de ferramenta.",
  "error.invalid-text": "Uma decisão precisa ter de 1 a 500 caracteres.",
  "error.limit-reached": "Este grupo já tem 100 decisões. Exclua uma primeiro.",
  "error.not-coordinator": "Só o Lead do grupo pode atribuir tarefas.",
  "error.coordinator-off": "O modo coordenador está desativado, ou o grupo não tem Lead.",
  "error.agent-not-found": "Esse agente não existe mais.",
  "error.agent-name-taken": "Outro agente já tem esse nome.",
  "error.group-project-required": "Escolha uma pasta para continuar este grupo.",
  "error.member-archived": "Esse agente está arquivado. Restaure-o primeiro.",
  "error.group-min-members": "Um grupo precisa de pelo menos 2 agentes.",
  "error.group-max-members": "Um grupo pode ter no máximo 10 agentes.",
  "error.agent-model-required": "Escolha um modelo para este agente.",
  "error.agent-model-unavailable":
    "Esse modelo não está disponível. Conecte o provedor dele ou escolha outro.",
  "error.agent-avatar-shape-taken": "Outro agente deste grupo já usa esse formato.",
  ...GROUP_TASK_TEXT_PT,
};

export const GROUP_ROOM_TEXT_ZH: Record<GroupTextKey, string> = {
  "common.cancel": "取消",
  "common.remove": "移除 {name}",
  "common.noModelConfigured": "未配置模型",
  "common.lead": "Lead",
  "room.hideActivity": "隐藏活动",
  "room.showActivity": "显示活动",
  "room.chooseFolder": "选择文件夹",
  "room.addAgent": "添加智能体",
  "blocked.projectRequired": "选择一个文件夹以继续此群组",
  "blocked.minMembers": "添加一位成员以继续",
  "header.stageTitle": "协作阶段（来自群组对话记录）",
  "header.owner": "负责人：",
  "header.stage": "阶段 · {stage}",
  "stage.Handoff": "交接",
  "stage.Review": "审核",
  "stage.Agree": "达成一致",
  "stage.Ready": "就绪",
  "header.noProject": "无项目",
  "header.search": "在对话中搜索",
  "header.clearSearch": "清除搜索",
  "header.stopTitle": "结束本链并停止正在运行的成员轮次",
  "header.stop": "停止",
  "header.groupActions": "群组操作",
  "header.moreAgents": "另外 {count} 个智能体：{names}",
  "popover.edit": "编辑 {name}",
  "popover.editShort": "编辑",
  "popover.agentPresence": "智能体状态",
  "popover.profileUnavailable": "{name} 的资料不可用。{presence}",
  "project.contextTitle": "此群组项目的共享项目地图",
  "project.mapping": "正在映射项目…",
  "project.ready": "项目上下文 · 就绪",
  "project.updating": "项目上下文 · 更新中",
  "project.needsRefresh": "项目上下文 · 需要刷新",
  "composer.updatePausedTitle": "Modus 更新期间已暂停",
  "composer.updatePausedBody":
    "消息已保存。待处理的任务会在重启后继续。被中断的运行会保留，方便你继续。",
  "composer.replying": "正在回复",
  "composer.kickoffTitle": "启动群组",
  "composer.kickoffHint": "目标 + 第一负责人——群组始终是唯一的事实来源。",
  "composer.kickoffOutcome": "目标",
  "composer.kickoffOutcomePlaceholder": "群组应该交付什么？",
  "composer.kickoffFirstOwner": "第一负责人",
  "composer.kickoffInsert": "插入启动内容",
  "composer.inputLabel": "给群组发消息",
  "composer.placeholder": "给群组发消息，用 @ 提及成员，可附加文件",
  "composer.attachFiles": "附加文件",
  "composer.executionMode": "执行模式",
  "composer.newTask": "新任务",
  "composer.complement": "补充",
  "composer.send": "发送",
  "attachments.readFailed": "无法读取文件。",
  "attachments.imageTooLarge": "图片过大（最大 {max} MB）",
  "attachments.imageUnreadable": "无法读取图片",
  "attachments.fileTooLarge": "文件过大（最大 {max} MB）",
  "attachments.pathUnavailable": "文件路径不可用",
  "row.filterExecution": "只显示此次执行的对话",
  "row.tokensTitle": "此次执行的预估 token 数（字符数 ÷ 4）",
  "row.tokens": "~{count} 个 token",
  "row.copyMessage": "复制消息",
  "row.replyToMessage": "回复消息",
  "row.reply": "回复",
  "row.you": "你",
  "row.member": "成员",
  "row.message": "消息",
  "row.replyingTo": "回复 {name}",
  "row.attachment": "附件",
  "row.earlierMessage": "较早的消息",
  "row.youInitial": "你",
  "row.human": "人类",
  "row.agent": "智能体",
  "status.turnFailed": "本轮失败",
  "status.turnStopped": "本轮已停止",
  "status.stoppedByYou": "已被你停止",
  "status.noNextOwner": "没有下一位负责人——请 @提及某人或提议达成一致",
  "status.worktreeReady": "Worktree 已就绪：`{branch}`",
  "status.archived": "{name} 已归档",
  "status.limitAgentMessages":
    "自动交接已暂停：本链已达到 {count} 条智能体消息的上限。已排队的轮次会继续完成。",
  "status.limitMemberWakes":
    "自动交接已暂停：本链中已有成员被唤醒 {count} 次。已排队的轮次会继续完成。",
  "status.limitInputTokens":
    "自动交接已暂停：本链已用完预估 {count}k token 的群组提示预算。已排队的轮次会继续完成。",
  "status.limitContext":
    "自动交接已暂停：该消息超出单轮预估 {count}k token 的群组上下文。已排队的轮次会继续完成。",
  "collab.handoffDefault": "@{name}，请从这里接手。",
  "collab.blocked": "受阻",
  "collab.blockedWith": "受阻——{text}",
  "collab.proposed": "已提议",
  "collab.proposedWith": "已提议——{text}",
  "collab.agreed": "已达成一致",
  "collab.agreedWith": "已达成一致——{text}",
  "activity.title": "活动",
  "activity.tokens": "Token",
  "activity.tokensSummary_one": "预估 · {count} 次执行共 ~{total}",
  "activity.tokensSummary_other": "预估 · {count} 次执行共 ~{total}",
  "activity.buttonActive": "活动（{count} 项进行中）",
  "activity.live": "实时",
  "activity.details": "详情",
  "activity.coordination": "协调",
  "activity.noHandoff": "没有进行中的交接",
  "activity.coordinatorOn": "协调模式已开启",
  "activity.freeCollab": "自由协作",
  "activity.turnOffCoordinator": "关闭协调模式",
  "activity.leadCoordinates": "由 Lead 协调未指定接收者的消息",
  "activity.addLeadForCoordinator": "添加 Lead 以启用协调模式",
  "activity.disable": "关闭",
  "activity.enable": "开启",
  "list.empty": "给群组写点什么。成员会接手合适的部分——或者 @提及某人。",
  "list.thisExecution": "此次执行",
  "list.showAll": "显示全部",
  "list.loadingOlder": "正在加载更早的消息…",
  "list.noMatches": "没有与“{query}”匹配的消息。",
  "list.newMessages_one": "{count} 条新消息",
  "list.newMessages_other": "{count} 条新消息",
  "day.today": "今天",
  "day.yesterday": "昨天",
  "decisions.title": "决策",
  "decisions.empty": "暂无决策",
  "decisions.confirmDelete": "再次点击以删除",
  "decisions.formerMember": "前成员",
  "decisions.delete": "删除",
  "result.outcome": "结果",
  "result.validations": "验证",
  "result.changedFiles": "已更改的文件",
  "result.openItems": "未完成事项",
  "live.progress": "进度",
  "kit.completed": "已完成",
  "kit.error": "出错",
  "kit.ready": "就绪",
  "kit.running": "运行中",
  "kit.steps": "步骤",
  "kit.image": "图片",
  "kit.text": "文本",
  "kit.file": "文件",
  "tasks.confirmCancel": "再次点击以取消",
  "tasks.inProgress": "进行中",
  "tasks.inReview": "审核中",
  "tasks.blocked": "已阻塞",
  "tasks.open": "待处理",
  "tasks.empty": "暂无任务。成员会在工作时创建任务。",
  "tasks.checklist": "清单",
  "tasks.progress": "已完成 {done}/{total}",
  "tasks.hideCancelled": "隐藏已取消",
  "tasks.showCancelled": "显示已取消（{count}）",
  "tasks.done": "已完成",
  "tasks.notDone": "未完成",
  "tasks.unassigned": "未分配",
  "tasks.cancel": "取消任务",
  "delivery.delivered": "已送达",
  "delivery.working": "工作中",
  "delivery.noReply": "无回复",
  "delivery.answered": "已回复",
  "manage.title": "管理成员",
  "manage.unknownProject": "未知项目",
  "manage.noFolder": "无文件夹",
  "manage.modelRequired": "请为新智能体选择一个模型。",
  "manage.agents": "智能体",
  "manage.removeTitle": "移除成员会删除其智能体",
  "manage.agentName": "智能体 {index} 的名字",
  "manage.agentRole": "智能体 {index} 的角色",
  "manage.namePlaceholder": "名字",
  "manage.rolePlaceholder": "角色（可选）",
  "manage.removeAgent": "移除智能体 {index}",
  "manage.modelForNew": "新智能体的模型",
  "manage.noLead": "无 Lead",
  "manage.saving": "正在保存…",
  "manage.save": "保存成员",
  "newGroup.title": "新群组",
  "newGroup.description": "在同一个文件夹中协作的智能体。",
  "newGroup.tabTemplates": "模板",
  "newGroup.tabCopy": "从其他群组复制",
  "newGroup.tabCustom": "新智能体",
  "newGroup.sourceTemplate": "模板",
  "newGroup.sourceCopy": "副本",
  "newGroup.sourceCustom": "自定义",
  "newGroup.folder": "文件夹",
  "newGroup.chooseFolder": "选择一个文件夹",
  "newGroup.addFolder": "添加文件夹…",
  "newGroup.name": "名字",
  "newGroup.collabPipeline": "协作流水线 · Planner → Builder → Reviewer",
  "newGroup.suggestedLead": "建议的 Lead",
  "newGroup.customizeLabel": "自定义 {name}",
  "newGroup.customize": "自定义",
  "newGroup.addLabel": "添加 {name}",
  "newGroup.add": "添加",
  "newGroup.copyHint":
    "添加一个独立副本：名字、角色、指令、模型和外观相同，但没有历史记录。编辑副本不会改变原智能体。",
  "newGroup.loadingAgents": "正在加载智能体…",
  "newGroup.noCopyable": "其他群组中还没有智能体。",
  "newGroup.copyLabel": "从 {group} 复制 {name}",
  "newGroup.copy": "复制",
  "newGroup.customHint":
    "自定义智能体需要名字和模型。角色和指令留空即可自动生成：系统会发送这里已选的角色，让新智能体与它们互补。",
  "newGroup.newAgent": "新智能体…",
  "newGroup.members": "成员",
  "newGroup.addAtLeast": "请至少添加 {count} 个智能体。",
  "newGroup.memberFallback": "成员 {index}",
  "newGroup.memberName": "成员 {index} 的名字",
  "newGroup.isLead": "{name} 是 Lead",
  "newGroup.makeLeadLabel": "将 {name} 设为 Lead",
  "newGroup.leadClear": "Lead（点击取消）",
  "newGroup.makeLead": "设为 Lead",
  "newGroup.noRole": "无角色",
  "newGroup.modelOf": "{name} 的模型",
  "newGroup.chooseModel": "选择一个模型",
  "newGroup.creating": "正在创建…",
  "newGroup.create": "创建",
  "hint.folder": "请为群组选择一个文件夹。",
  "hint.min": "一个群组至少需要 {count} 个智能体。",
  "hint.max": "一个群组最多只能有 {count} 个智能体。",
  "hint.names": "每个智能体都需要不同的名字。",
  "hint.emptyName": "每个智能体都需要名字。",
  "hint.model": "请为每个非模板智能体选择一个模型。",
  "sidebar.removeProjectGroups_one": "这也会删除 1 个群组及其智能体和聊天：{names}",
  "sidebar.removeProjectGroups_other": "这也会删除 {count} 个群组及其智能体和聊天：{names}",
  "sidebar.deleteGroup_one": "这会删除它的 1 个智能体、相关聊天和所有群组消息",
  "sidebar.deleteGroup_other": "这会删除它的 {count} 个智能体、相关聊天和所有群组消息",
  "error.group-not-found": "此群组已不存在。",
  "error.workspace-not-found": "所选项目已不存在。",
  "error.session-not-found": "所选聊天中有一个已不存在。",
  "error.message-not-found": "该消息不属于此群组。",
  "error.task-not-found": "该任务已不存在。",
  "error.decision-not-found": "该决策已不存在。",
  "error.workspace-mismatch":
    "每位成员都必须属于群组的项目（群组没有项目时，成员也不能有文件夹）。",
  "error.already-in-group": "所选聊天中有一个已在其他群组中。",
  "error.subagent-session": "子智能体聊天不能加入群组。",
  "error.archived-session": "已归档的聊天不能加入群组。请先恢复该聊天。",
  "error.not-a-member": "该聊天不是此群组的成员。",
  "error.invalid-value": "部分群组信息无效。",
  "error.not-owner": "只有任务负责人可以执行此操作。",
  "error.not-reviewer": "只有任务审核人可以执行此操作。",
  "error.task-taken": "该任务已有负责人。",
  "error.invalid-transition": "该任务无法从当前状态切换到该状态。",
  "error.self-review": "任务负责人不能审核自己的任务。",
  "error.ambiguous-member": "有多位成员同名。请按 id 选择聊天。",
  "error.no-git-project": "成员 worktree 需要群组的项目是 Git 仓库。",
  "error.branch-checked-out": "该成员的分支已在另一个文件夹中检出。请先将那里切换到其他分支。",
  "error.call-alone": "成员必须用一条不调用其他工具的消息来启动其 worktree。",
  "error.invalid-text": "决策文本需要 1 到 500 个字符。",
  "error.limit-reached": "此群组已有 100 条决策。请先删除一条。",
  "error.not-coordinator": "只有群组的 Lead 可以分配任务。",
  "error.coordinator-off": "协调模式已关闭，或群组没有 Lead。",
  "error.agent-not-found": "该智能体已不存在。",
  "error.agent-name-taken": "已有其他智能体使用该名字。",
  "error.group-project-required": "选择一个文件夹以继续此群组。",
  "error.member-archived": "该智能体已归档。请先恢复它。",
  "error.group-min-members": "一个群组至少需要 2 个智能体。",
  "error.group-max-members": "一个群组最多只能有 10 个智能体。",
  "error.agent-model-required": "请为此智能体选择一个模型。",
  "error.agent-model-unavailable": "该模型不可用。请连接其提供商或选择其他模型。",
  "error.agent-avatar-shape-taken": "此群组中已有其他智能体使用该形状。",
  ...GROUP_TASK_TEXT_ZH,
};
