export const antigravityExpectedMetadata = [
  {
    id: "antigravity-gemini-3-pro",
    name: "Gemini 3 Pro (Antigravity)",
    quotaRoute: "antigravity",
    contextWindow: 1048576,
    maxOutputTokens: 65535,
    reasoningSupported: true,
    reasoningVariants: { low: { thinkingLevel: "low" }, high: { thinkingLevel: "high" } },
    sourceModalities: ["text", "image", "pdf"],
    input: ["text", "image"],
  },
  {
    id: "antigravity-gemini-3.1-pro",
    name: "Gemini 3.1 Pro (Antigravity)",
    quotaRoute: "antigravity",
    contextWindow: 1048576,
    maxOutputTokens: 65535,
    reasoningSupported: true,
    reasoningVariants: { low: { thinkingLevel: "low" }, high: { thinkingLevel: "high" } },
    sourceModalities: ["text", "image", "pdf"],
    input: ["text", "image"],
  },
  {
    id: "antigravity-gemini-3-flash",
    name: "Gemini 3 Flash (Antigravity)",
    quotaRoute: "antigravity",
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    reasoningSupported: true,
    reasoningVariants: {
      minimal: { thinkingLevel: "minimal" },
      low: { thinkingLevel: "low" },
      medium: { thinkingLevel: "medium" },
      high: { thinkingLevel: "high" },
    },
    sourceModalities: ["text", "image", "pdf"],
    input: ["text", "image"],
  },
  {
    id: "antigravity-claude-sonnet-4-6",
    name: "Claude Sonnet 4.6 (Antigravity)",
    quotaRoute: "antigravity",
    contextWindow: 200000,
    maxOutputTokens: 64000,
    reasoningSupported: false,
    sourceModalities: ["text", "image", "pdf"],
    input: ["text", "image"],
  },
  {
    id: "antigravity-claude-opus-4-6-thinking",
    name: "Claude Opus 4.6 Thinking (Antigravity)",
    quotaRoute: "antigravity",
    contextWindow: 200000,
    maxOutputTokens: 64000,
    reasoningSupported: true,
    reasoningVariants: { low: { thinkingBudget: 8192 }, max: { thinkingBudget: 32768 } },
    sourceModalities: ["text", "image", "pdf"],
    input: ["text", "image"],
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash (Gemini CLI)",
    quotaRoute: "gemini-cli",
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    reasoningSupported: true,
    sourceModalities: ["text", "image", "pdf"],
    input: ["text", "image"],
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro (Gemini CLI)",
    quotaRoute: "gemini-cli",
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    reasoningSupported: true,
    sourceModalities: ["text", "image", "pdf"],
    input: ["text", "image"],
  },
  {
    id: "gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview (Gemini CLI)",
    quotaRoute: "gemini-cli",
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    reasoningSupported: true,
    sourceModalities: ["text", "image", "pdf"],
    input: ["text", "image"],
  },
  {
    id: "gemini-3-pro-preview",
    name: "Gemini 3 Pro Preview (Gemini CLI)",
    quotaRoute: "gemini-cli",
    contextWindow: 1048576,
    maxOutputTokens: 65535,
    reasoningSupported: true,
    sourceModalities: ["text", "image", "pdf"],
    input: ["text", "image"],
  },
  {
    id: "gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview (Gemini CLI)",
    quotaRoute: "gemini-cli",
    contextWindow: 1048576,
    maxOutputTokens: 65535,
    reasoningSupported: true,
    sourceModalities: ["text", "image", "pdf"],
    input: ["text", "image"],
  },
  {
    id: "gemini-3.1-pro-preview-customtools",
    name: "Gemini 3.1 Pro Preview Custom Tools (Gemini CLI)",
    quotaRoute: "gemini-cli",
    contextWindow: 1048576,
    maxOutputTokens: 65535,
    reasoningSupported: true,
    sourceModalities: ["text", "image", "pdf"],
    input: ["text", "image"],
  },
] as const;
