export const commandCodeExpectedMetadata = [
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    tier: "premium",
    reasoningSupported: false,
    toolCallsSupported: true,
    contextWindow: 200000,
    maxOutputTokens: 8192,
  },
  {
    id: "claude-opus-4-7",
    name: "Claude Opus 4.7",
    tier: "premium",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 32000,
  },
  {
    id: "claude-opus-4-8",
    name: "Claude Opus 4.8",
    tier: "premium",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 1000000,
  },
  {
    id: "claude-opus-5",
    name: "Claude Opus 5",
    tier: "premium",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 1000000,
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    tier: "premium",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 16000,
  },
  {
    id: "claude-sonnet-5",
    name: "Claude Sonnet 5",
    tier: "premium",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 1000000,
  },
  {
    id: "claude-fable-5",
    name: "Claude Fable 5",
    tier: "premium",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 1000000,
  },
  {
    id: "gpt-5.3-codex",
    name: "GPT-5.3 Codex",
    tier: "premium",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 400000,
    maxOutputTokens: 400000,
  },
  {
    id: "gpt-5.4",
    name: "GPT-5.4",
    tier: "premium",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1050000,
    maxOutputTokens: 1050000,
  },
  {
    id: "gpt-5.4-mini",
    name: "GPT-5.4 Mini",
    tier: "premium",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 400000,
    maxOutputTokens: 400000,
  },
  {
    id: "gpt-5.5",
    name: "GPT-5.5",
    tier: "premium",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 400000,
    maxOutputTokens: 400000,
  },
  {
    id: "gpt-5.6-luna",
    name: "GPT-5.6 Luna",
    tier: "premium",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1050000,
    maxOutputTokens: 1050000,
  },
  {
    id: "gpt-5.6-sol",
    name: "GPT-5.6 Sol",
    tier: "premium",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1050000,
    maxOutputTokens: 1050000,
  },
  {
    id: "gpt-5.6-terra",
    name: "GPT-5.6 Terra",
    tier: "premium",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1050000,
    maxOutputTokens: 1050000,
  },
  {
    id: "deepseek/deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
  },
  {
    id: "deepseek/deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
  },
  {
    id: "google/gemini-3.1-flash-lite",
    name: "Gemini 3.1 Flash Lite",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
  },
  {
    id: "google/gemini-3.5-flash",
    name: "Gemini 3.5 Flash",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
  },
  {
    id: "google/gemini-3.5-flash-lite",
    name: "Gemini 3.5 Flash Lite",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
  },
  {
    id: "google/gemini-3.6-flash",
    name: "Gemini 3.6 Flash",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 1000000,
  },
  {
    id: "google/gemini-3.7-flash",
    name: "Gemini 3.7 Flash",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 1000000,
  },
  {
    id: "meta/muse-spark-1.1",
    name: "Muse Spark 1.1",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 262144,
    maxOutputTokens: 262144,
  },
  {
    id: "meta/muse-spark-1.2",
    name: "Muse Spark 1.2",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 262144,
    maxOutputTokens: 262144,
  },
  {
    id: "meta/muse-spark-1.2-contributor",
    name: "Muse Spark 1.2 Contributor",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 262144,
    maxOutputTokens: 262144,
  },
  {
    id: "MiniMaxAI/MiniMax-M2.5",
    name: "MiniMax M2.5",
    tier: "open-source",
    reasoningSupported: false,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
  },
  {
    id: "MiniMaxAI/MiniMax-M2.7",
    name: "MiniMax M2.7",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
  },
  {
    id: "MiniMaxAI/MiniMax-M3",
    name: "MiniMax M3",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1048576,
    maxOutputTokens: 1048576,
  },
  {
    id: "moonshotai/Kimi-K2.5",
    name: "Kimi K2.5",
    tier: "open-source",
    reasoningSupported: false,
    toolCallsSupported: true,
    contextWindow: 262144,
    maxOutputTokens: 131072,
  },
  {
    id: "moonshotai/Kimi-K2.6",
    name: "Kimi K2.6",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 262144,
    maxOutputTokens: 131072,
  },
  {
    id: "moonshotai/Kimi-K2.7-Code",
    name: "Kimi K2.7 Code",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 262144,
    maxOutputTokens: 262144,
  },
  {
    id: "moonshotai/Kimi-K2.7-Code-Highspeed",
    name: "Kimi K2.7 Code Highspeed",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 262144,
    maxOutputTokens: 262144,
  },
  {
    id: "moonshotai/Kimi-K3",
    name: "Kimi K3",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1048576,
    maxOutputTokens: 1048576,
  },
  {
    id: "nvidia/nemotron-3-ultra-550b-a55b",
    name: "Nemotron 3 Ultra",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 262144,
    maxOutputTokens: 262144,
  },
  {
    id: "poolside/laguna-s-2.1-free",
    name: "Laguna S 2.1",
    tier: "open-source",
    reasoningSupported: false,
    toolCallsSupported: true,
    contextWindow: 262144,
    maxOutputTokens: 262144,
  },
  {
    id: "Qwen/Qwen3.6-Max-Preview",
    name: "Qwen 3.6 Max Preview",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
  },
  {
    id: "Qwen/Qwen3.6-Plus",
    name: "Qwen 3.6 Plus",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
  },
  {
    id: "Qwen/Qwen3.7-Flash",
    name: "Qwen 3.7 Flash",
    tier: "open-source",
    reasoningSupported: false,
    toolCallsSupported: true,
    contextWindow: 128000,
    maxOutputTokens: 16000,
  },
  {
    id: "Qwen/Qwen3.7-Max",
    name: "Qwen 3.7 Max",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
  },
  {
    id: "Qwen/Qwen3.7-Plus",
    name: "Qwen 3.7 Plus",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
  },
  {
    id: "Qwen/Qwen3.8-Max",
    name: "Qwen 3.8 Max",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 262144,
    maxOutputTokens: 262144,
  },
  {
    id: "sakana/fugu-ultra",
    name: "Fugu Ultra",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 128000,
    maxOutputTokens: 128000,
  },
  {
    id: "stepfun/Step-3.5-Flash",
    name: "Step 3.5 Flash",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
  },
  {
    id: "stepfun/Step-3.7-Flash",
    name: "Step 3.7 Flash",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
  },
  {
    id: "tencent/hy3-paid",
    name: "Tencent Hy3",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 128000,
    maxOutputTokens: 64000,
  },
  {
    id: "thinkingmachines/inkling",
    name: "Inkling",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 262144,
    maxOutputTokens: 262144,
  },
  {
    id: "thinkingmachines/inkling-small",
    name: "Inkling Small",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 262144,
    maxOutputTokens: 262144,
  },
  {
    id: "xai/grok-4.5",
    name: "Grok 4.5",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 262144,
    maxOutputTokens: 262144,
  },
  {
    id: "xai/grok-4.6",
    name: "Grok 4.6",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 262144,
    maxOutputTokens: 262144,
  },
  {
    id: "xiaomi/mimo-v2.5",
    name: "MiMo V2.5",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 262144,
    maxOutputTokens: 262144,
  },
  {
    id: "xiaomi/mimo-v2.5-pro",
    name: "MiMo V2.5 Pro",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 262144,
    maxOutputTokens: 262144,
  },
  {
    id: "zai-org/GLM-5",
    name: "GLM-5",
    tier: "open-source",
    reasoningSupported: false,
    toolCallsSupported: true,
    contextWindow: 200000,
    maxOutputTokens: 131072,
  },
  {
    id: "zai-org/GLM-5.1",
    name: "GLM-5.1",
    tier: "open-source",
    reasoningSupported: false,
    toolCallsSupported: true,
    contextWindow: 200000,
    maxOutputTokens: 131072,
  },
  {
    id: "zai-org/GLM-5.2",
    name: "GLM-5.2",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1048576,
    maxOutputTokens: 1048576,
  },
  {
    id: "zai-org/GLM-5.2-Fast",
    name: "GLM-5.2 Fast",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 1048576,
    maxOutputTokens: 1048576,
  },
  {
    id: "zai-org/GLM-5.3",
    name: "GLM-5.3",
    tier: "open-source",
    reasoningSupported: true,
    toolCallsSupported: true,
    contextWindow: 202752,
    maxOutputTokens: 202752,
  },
] as const;
